"use client";
import { ChangeEvent, useEffect, useState } from "react";
import { WorkspaceNav } from "../../../../../components/workspace";
import { api } from "../../../../../lib/api";

type Doc = { id: string; filename: string; archive_member?: string; size_bytes: number; page_count: number; warnings: string[]; drawing: { disciplines: string[]; sheet_labels: string[]; is_drawing_candidate: boolean } };
type Analysis = { certification: string; evidence_points: number; target_score: number; total_possible_points: number; confidence: number; drawing_summary: { document_count: number; drawing_candidates: number; disciplines: string[]; sheet_labels: string[]; warnings: string[] }; findings: { credit_id: string; severity: string; text: string; recommended_action: string; evidence_refs: string[] }[]; limitations: string[] };
export default function Documents({ params }: { params: Promise<{ projectId: string }> }) { const [projectId, setProjectId] = useState(""); const [files, setFiles] = useState<FileList | null>(null); const [docs, setDocs] = useState<Doc[]>([]); const [analysis, setAnalysis] = useState<Analysis | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); useEffect(() => { params.then(({ projectId: id }) => { setProjectId(id); api<Doc[]>(`/api/projects/${id}/documents`).then(setDocs).catch(() => undefined); }); }, [params]);
  const selectFiles = (e: ChangeEvent<HTMLInputElement>) => setFiles(e.target.files);
  async function upload() { if (!files || !projectId) return; setBusy(true); setMessage(""); try { const form = new FormData(); Array.from(files).forEach((file) => form.append("files", file)); const result = await api<{ files: { uploaded: Doc[] }[] }>(`/api/projects/${projectId}/documents/upload-batch`, { method: "POST", body: form }); setDocs((old) => [...old, ...result.files.flatMap((x) => x.uploaded)]); setMessage(`Uploaded and extracted ${result.files.reduce((n, x) => n + x.uploaded.length, 0)} file(s).`); } catch (e) { setMessage(e instanceof Error ? e.message : "Upload failed"); } finally { setBusy(false); } }
  async function runAnalysis() { setBusy(true); try { setAnalysis(await api<Analysis>(`/api/projects/${projectId}/analyze`, { method: "POST", body: JSON.stringify({ known_constraints: [], document_ids: [] }) })); } catch (e) { setMessage(e instanceof Error ? e.message : "Analysis failed"); } finally { setBusy(false); } }
  return <main className="shell"><WorkspaceNav projectId={projectId}/><div className="page-head"><div><span className="eyebrow">Evidence workspace</span><h1>Upload & automatic assessment</h1><p>ZIP packages are safely unpacked. PDFs, text files and drawing filenames are indexed; native CAD/BIM geometry remains metadata-only unless a specialist parser is connected.</p></div></div><section className="card upload-box"><input type="file" multiple accept=".pdf,.zip,.txt,.md,.csv,.json,.xml,.ifc,.dxf,.dwg,.rvt,.rfa,.png,.jpg,.jpeg" onChange={selectFiles}/><div className="actions"><button onClick={upload} disabled={busy || !files}>{busy ? "Processing…" : "Upload and extract"}</button><button className="secondary" onClick={runAnalysis} disabled={busy || !projectId}>Run LEED assessment</button></div>{message && <p className="status">{message}</p>}</section><section><h2>Indexed evidence ({docs.length})</h2><div className="grid">{docs.map((doc) => <article className="card" key={doc.id}><h3>{doc.filename}</h3><small>{Math.round(doc.size_bytes / 1024)} KB · {doc.page_count || 0} pages {doc.archive_member ? `· ZIP: ${doc.archive_member}` : ""}</small><p>{doc.drawing?.disciplines?.join(", ") || "discipline not inferred"}</p>{doc.drawing?.sheet_labels?.length > 0 && <p className="tag">Sheets: {doc.drawing.sheet_labels.slice(0, 8).join(", ")}</p>}{doc.warnings?.map((w) => <p className="warn" key={w}>{w}</p>)}</article>)}{docs.length === 0 && <div className="card"><p>Select one or more files, including a ZIP project package.</p></div>}</div></section>{analysis && <section className="results"><div className="score-hero"><div><span className="eyebrow">Indicative result</span><h2>{analysis.certification}</h2><p>{analysis.target_score} target points / {analysis.total_possible_points} available · confidence {Math.round(analysis.confidence * 100)}%</p></div><strong>{analysis.evidence_points}</strong></div><div className="card"><h2>Drawing recognition</h2><p>{analysis.drawing_summary.drawing_candidates} drawing candidates across {analysis.drawing_summary.document_count} indexed files.</p><p>{analysis.drawing_summary.disciplines.join(", ") || "No discipline inferred yet"}</p><p>Sheets: {analysis.drawing_summary.sheet_labels.join(", ") || "None detected"}</p></div><h2>Findings</h2>{analysis.findings.slice(0, 15).map((finding) => <article className={`finding ${finding.severity}`} key={finding.credit_id}><b>{finding.credit_id}</b> <span className="tag">{finding.severity}</span><p>{finding.text}</p><p><b>Action:</b> {finding.recommended_action}</p></article>)}<div className="card"><h3>Limitations</h3>{analysis.limitations.map((item) => <p className="warn" key={item}>{item}</p>)}</div></section>}</main>; }
